//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SercanTestCheckout
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Deals
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> DiscountAmountPercent { get; set; }
        public Nullable<int> DiscountAmountPrice { get; set; }
    }
}
